---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run the Django syncdb command
  django_manage:
    command: syncdb
    app_path: "{{ project_path }}/{{ project_name }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django

- name: Load initial admin user
  django_manage:
    command: "loaddata aggregator/fixtures/user.json"
    app_path: "{{ project_path }}/{{ project_name }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django

- name: Load initial demo services
  django_manage:
    command: "loaddata aggregator/fixtures/aggregator.json"
    app_path: "{{ project_path }}/{{ project_name }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}/{{ project_name }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django
