sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.8.0

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y docker-engine
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build django

script:
  - docker-compose run django python python manage.py test hypermap.aggregator --settings=hypermap.settings.test --failfast

branches:
  only:
    - master
    - registry
